version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "swaggerloaf"
github_repo = "demoboy-rocks"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::409556542397:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-2BstN2p51Sq7"
cloudformation_execution_role = "arn:aws:iam::409556542397:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-86FtpJ2W9Rfk"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-9womaurq3liv"
image_repository = ""
region = "us-east-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::409556542397:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-8faVOpxeisaA"
cloudformation_execution_role = "arn:aws:iam::409556542397:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-NZLKsBY3g6rr"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-ugevyi5jdllx"
image_repository = ""
region = "us-east-2"
